(TeX-add-style-hook
 "TNFSHC++"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "12pt" "a4paper")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem")))
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings")
   (LaTeX-add-labels
    "cpp_execution"
    "sec:org1eedfc2"
    "sec:org216aff5"
    "sec:org90bdd14"
    "fig:CNE"
    "sec:org690b25e"
    "sec:org29383e6"
    "sec:orgc97e2e6"
    "sec:org38b5eb9"
    "sec:org59458ba"
    "sec:orgcc2d69a"
    "sec:org4309eb3"
    "cpp_arch"
    "sec:orgc69b111"
    "sec:orgca71d68"
    "sec:org524da2e"
    "cpp_output"
    "sec:org3526fc2"
    "cpp_printf"
    "sec:orgf2b3b71"
    "sec:orgfea44a5"
    "sec:orgbbc3c56"
    "cpp_variables"
    "sec:orgdd59134"
    "VarDec"
    "sec:orgf96ea5b"
    "fig:vic"
    "sec:org0fd607b"
    "cpp_variable_types"
    "cpp_input"
    "sec:orgc55f45a"
    "sec:org97f6cf8"
    "sec:org641caca"
    "sec:orgf1c9ee1"
    "cpp_operation"
    "sec:org6f7c5e0"
    "sec:org0ed53bb"
    "cpp_cond_operation"
    "sec:orgd21a317"
    "sec:org4405b6d"
    "sec:orgd99e69a"
    "sec:orgaefce76"
    "cpp_ifelse"
    "sec:org6db8e12"
    "sec:orgf0e56fe"
    "sec:org4f3e54e"
    "sec:org1991e74"
    "sec:orgbdc59c0"
    "sec:org42e6e4a"
    "sec:org84cbf87"
    "sec:orgd2cadd7"
    "sec:orgaeda786"
    "sec:orgd920c03"
    "sec:orge3aee2e"
    "sec:org6849257"
    "sec:orgddf2546"
    "sec:org1f757eb"
    "sec:orgf8aa5e2"
    "cpp_multi_conditions"
    "sec:org3e99e7e"
    "sec:orge5cbdb2"
    "sec:org4168ef5"
    "sec:org37303e0"
    "sec:org3dbc6a9"
    "cpp_for_loop"
    "sec:orge834a32"
    "sec:org5be9f7e"
    "sec:org18b9502"
    "cpp_nested_for"
    "sec:org8a8c433"
    "sec:org251efd1"
    "cpp_while"
    "sec:orgbc54fe0"
    "sec:orge1cce0d"
    "sec:org2a12ebb"
    "sec:org83b7f35"
    "cpp_arrays"
    "cpp_functions"
    "sec:orgb78cd4a"
    "sec:org691a6bc"
    "sec:org45c44fc"
    "cpp_struct"
    "sec:org96b4c24"))
 :latex)

