(TeX-add-style-hook
 "TNFSHC++"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("ulem" "normalem") ("helvet" "scaled") ("geometry" "margin=2cm" "margin=1.0in") ("natbib" "numbers" "sort&compress" "square") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "titlesec"
    "helvet"
    "courier"
    "natbib"
    "glossaries"
    "setspace"
    "enumitem"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "algorithm"
    "algorithmic"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins")
   (TeX-add-symbols
    "sectionbreak")
   (LaTeX-add-labels
    "cpp_execution"
    "sec:orgea7c977"
    "sec:org67c1a0f"
    "sec:org42d37f8"
    "sec:org5e50302"
    "sec:orga835070"
    "sec:org338db69"
    "sec:org178034b"
    "sec:org0c43f6f"
    "sec:org9a30d95"
    "sec:org19d8c2e"
    "cpp_arch"
    "sec:orgd2a3743"
    "sec:orga4f5fe6"
    "sec:org30585a1"
    "cpp_output"
    "sec:org8b8ca99"
    "cpp_printf"
    "sec:orgcf4d68d"
    "sec:org54501d7"
    "sec:org6901250"
    "cpp_variables"
    "sec:orgc3eba6c"
    "VarDec"
    "sec:org1c896de"
    "fig:vic"
    "sec:org3f1a066"
    "cpp_variable_types"
    "sec:orgff90167"
    "sec:org0c525c8"
    "sec:org1b0a1d1"
    "cpp_input"
    "sec:org55474ab"
    "sec:org8702716"
    "sec:orga8232a0"
    "sec:orgb73e084"
    "cpp_operation"
    "sec:orgb0f36cc"
    "sec:orge127250"
    "sec:orgcf37165"
    "cpp_cond_operation"
    "sec:org17e8bfd"
    "sec:orgcbdc0d6"
    "sec:org576d6ad"
    "sec:org74a009f"
    "cpp_ifelse"
    "sec:org476face"
    "sec:org27dff94"
    "sec:orgba322ce"
    "CPP_ifelse_practice1"
    "sec:orgb8a9bc1"
    "sec:orgd5cc85d"
    "sec:orgaa324e8"
    "sec:org3af9dc0"
    "sec:org73946bf"
    "sec:orga1f488c"
    "sec:org956bf1a"
    "sec:orgb27c750"
    "sec:org25399f1"
    "sec:org29bb9d2"
    "sec:org28353e1"
    "sec:org412af0d"
    "sec:org8daa4ab"
    "sec:org4c8b5c8"
    "sec:orgf2f733a"
    "sec:org04a75ea"
    "sec:orgfe8f385"
    "sec:orgc3aa67a"
    "sec:orgc59f4aa"
    "sec:org95af7e4"
    "sec:org0417630"
    "sec:orgb7f70ef"
    "cpp_multi_conditions"
    "sec:org9076e44"
    "sec:org474bbe9"
    "cpp_for_loop"
    "sec:org9c46749"
    "sec:org141ed35"
    "sec:org9f53273"
    "sec:org10e17d3"
    "cpp_nested_for"
    "sec:org93131b2"
    "sec:org01c6e8f"
    "sec:org87ac3ac"
    "sec:org218cc5b"
    "sec:orge262438"
    "sec:org73e834f"
    "sec:org78564ce"
    "cpp_while"
    "sec:orgfe469fd"
    "sec:orgd6f30c2"
    "sec:orge686c40"
    "sec:orgb689baa"
    "sec:org15b4f00"
    "sec:orgc9b354d"
    "sec:org859c12a"
    "sec:orgc3604d9"
    "cpp_arrays"
    "sec:org88029b4"
    "sec:org47fa6f3"
    "sec:org8dcb1d6"
    "fig:Array"
    "sec:orge1edd9e"
    "sec:orgdd0f20f"
    "sec:orga16e096"
    "sec:orgf288421"
    "sec:org72e01fd"
    "sec:org3b58370"
    "fig:Memory-Value"
    "sec:org47b7a8b"
    "sec:org5e5dbcc"
    "sec:org0a4026e"
    "sec:org8927926"
    "sec:orgf7c1242"
    "sec:orgfdc5fa9"
    "sec:org0519fc6"
    "cpp_functions"
    "sec:orgc43509a"
    "sec:org3fa11e0"
    "sec:org9bd285c"
    "cpp_struct"
    "sec:org69340d5"))
 :latex)

