(TeX-add-style-hook
 "TNFSHC++"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "listing"
    "algorithm"
    "algorithmic"
    "natbib"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins"
    "enumitem")
   (LaTeX-add-labels
    "cpp_execution"
    "sec:org1361f27"
    "sec:org75d5bd3"
    "sec:org3d74ad8"
    "fig:CNE"
    "sec:org0feee1c"
    "sec:org4b324e3"
    "sec:orgca0bc95"
    "sec:orgbef110a"
    "sec:org641c989"
    "sec:org0e86794"
    "sec:org69247cf"
    "cpp_arch"
    "sec:orge8d5975"
    "sec:org52c61fc"
    "sec:org63f5b0d"
    "cpp_output"
    "sec:org7d3137e"
    "cpp_printf"
    "sec:org36baa3c"
    "sec:org7163020"
    "sec:org736fe49"
    "cpp_variables"
    "sec:org148ac3e"
    "VarDec"
    "sec:orgbaf8305"
    "fig:vic"
    "sec:org44eaa45"
    "cpp_variable_types"
    "sec:orgf75e96e"
    "sec:org5057633"
    "sec:orgde13426"
    "cpp_input"
    "sec:org86a8755"
    "sec:org79a531f"
    "sec:org3ec00b8"
    "sec:org99712ad"
    "cpp_operation"
    "sec:org39682db"
    "sec:orga6a6470"
    "cpp_cond_operation"
    "sec:orgbcc757d"
    "sec:org43deb11"
    "sec:orgd87bff9"
    "sec:orgb181672"
    "cpp_ifelse"
    "sec:org2ac821a"
    "sec:org0271f59"
    "sec:org23fcfdb"
    "CPP_ifelse_practice1"
    "sec:org94bd62a"
    "sec:org77ee4bb"
    "sec:orgfb3025b"
    "sec:org8d2ba85"
    "sec:orgbc86832"
    "sec:org7c872cd"
    "sec:org08aeda7"
    "sec:orgf968ba7"
    "sec:orgc9434ed"
    "sec:org852bf94"
    "sec:org120e75e"
    "sec:org1d9c009"
    "sec:orgcd8b5a1"
    "sec:orgbb4531b"
    "sec:org291b1a8"
    "sec:orgdd97845"
    "sec:org8af2c2a"
    "sec:orge1668ad"
    "sec:org856620b"
    "sec:orgb867597"
    "sec:orgee6f398"
    "sec:org2a25281"
    "cpp_multi_conditions"
    "sec:org6ec2383"
    "sec:orgd33fa38"
    "cpp_for_loop"
    "sec:org481a331"
    "sec:orgfd68aa5"
    "sec:org49afff7"
    "sec:org31f7a7d"
    "cpp_nested_for"
    "sec:org68b1524"
    "sec:org970fedd"
    "sec:org3a51b23"
    "sec:org1343427"
    "sec:org5a627f4"
    "sec:org3b97838"
    "sec:org9302736"
    "cpp_while"
    "sec:org76af666"
    "sec:org2bcc2b8"
    "sec:orgb502ff9"
    "sec:org258cad5"
    "sec:orgffb98d4"
    "sec:org2bc27ff"
    "sec:org1e7dea5"
    "sec:orgea3c92a"
    "cpp_arrays"
    "sec:org8f4b6ca"
    "sec:org75b466a"
    "sec:org76940ac"
    "fig:Array"
    "sec:orgdd3df1d"
    "sec:org324455a"
    "sec:org33918af"
    "sec:orgf944299"
    "sec:org9a1676e"
    "sec:orgbd5e65c"
    "fig:Memory-Value"
    "sec:org87d3522"
    "sec:orgf35ba87"
    "sec:orgc351cfa"
    "sec:org2b38cb7"
    "sec:org60ba767"
    "cpp_functions"
    "sec:org31ece06"
    "sec:org0156cd9"
    "sec:org3de32f0"
    "cpp_struct"
    "sec:orgf1e724e")
   (LaTeX-add-color-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

