(TeX-add-style-hook
 "TNFSHC++"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("ulem" "normalem") ("helvet" "scaled") ("geometry" "margin=2cm" "margin=1.0in") ("natbib" "numbers" "sort&compress" "square") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "titlesec"
    "helvet"
    "courier"
    "natbib"
    "glossaries"
    "setspace"
    "enumitem"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "algorithm"
    "algorithmic"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins")
   (TeX-add-symbols
    "sectionbreak")
   (LaTeX-add-labels
    "cpp_execution"
    "sec:org3d9b562"
    "sec:org0c1f780"
    "sec:org23623c1"
    "sec:orgd99603b"
    "sec:org5c7acfd"
    "sec:org9847af4"
    "sec:orgaf27806"
    "sec:orga273dfa"
    "sec:orgd99dfeb"
    "sec:org7e1540d"
    "cpp_arch"
    "sec:org5cd5337"
    "sec:orgb644081"
    "sec:org0583639"
    "cpp_output"
    "sec:orgff408ef"
    "cpp_printf"
    "sec:org2daab1e"
    "sec:org3159465"
    "sec:org3160745"
    "cpp_variables"
    "sec:org0c794d3"
    "VarDec"
    "sec:org70830e7"
    "fig:vic"
    "sec:org2e13425"
    "cpp_variable_types"
    "sec:orgd33a2b8"
    "sec:orgd91b97d"
    "sec:org7258fc3"
    "cpp_input"
    "sec:org7b49fd1"
    "sec:org65c97c0"
    "sec:org74e6dcf"
    "sec:org4038ad1"
    "cpp_operation"
    "sec:orgf184405"
    "sec:org586e612"
    "sec:orgfd9cfd6"
    "cpp_cond_operation"
    "sec:orgfdaba84"
    "sec:org85b4e5a"
    "sec:orgd84c92e"
    "sec:orgb585119"
    "cpp_ifelse"
    "sec:org195ae2c"
    "sec:org042cc73"
    "sec:org6faba50"
    "CPP_ifelse_practice1"
    "sec:org4a141b9"
    "sec:orgfcef482"
    "sec:org014645b"
    "sec:org290b754"
    "sec:org2b2e5fe"
    "sec:org7f69a42"
    "sec:org0846d26"
    "sec:orgcdff382"
    "sec:orge1fca6d"
    "sec:org034850b"
    "sec:org639602f"
    "sec:org964ab84"
    "sec:org881f393"
    "sec:org00bb899"
    "sec:org784a727"
    "sec:org470b48a"
    "sec:org08f3740"
    "sec:org9df117a"
    "sec:orgf57987f"
    "sec:orge744b5e"
    "sec:org84cb0ea"
    "sec:org2ac9996"
    "cpp_multi_conditions"
    "sec:orgcb123bf"
    "sec:orgd5e4b5c"
    "cpp_for_loop"
    "sec:org89bb8a1"
    "sec:org029ae4a"
    "sec:orgba33329"
    "sec:org6e5eedf"
    "flag_variable"
    "sec:org19e67b0"
    "sec:orgf86aed2"
    "sec:org2c8f2eb"
    "sec:orgbce519d"
    "cpp_nested_for"
    "sec:org1f3d564"
    "sec:org086a905"
    "sec:org4f41abd"
    "sec:org2240be2"
    "sec:org5f99f43"
    "sec:org66c1f62"
    "sec:orge0a4490"
    "cpp_while"
    "sec:org6940792"
    "sec:org4c6519b"
    "sec:org573c1be"
    "sec:org74e1082"
    "sec:orgb34f6af"
    "sec:orgc78905c"
    "sec:org65a6de9"
    "sec:orga70ae16"
    "cpp_arrays"
    "sec:org8ffc899"
    "sec:orgfa78a43"
    "sec:orgb8083f3"
    "fig:Array"
    "sec:org20ab84b"
    "sec:org40a82e9"
    "sec:org11d345b"
    "sec:org5315ff2"
    "sec:org0f2f40e"
    "sec:org2540741"
    "fig:Memory-Value"
    "sec:org47a4627"
    "sec:org2fefba2"
    "sec:org0303c3b"
    "sec:org7ec4313"
    "sec:org8108c98"
    "sec:org8439b8d"
    "sec:org59b8a58"
    "cpp_string"
    "sec:org9dbb22a"
    "sec:orgcb2e27a"
    "sec:org2edf7d7"
    "sec:org050fd5e"
    "sec:org6bef0ae"
    "sec:orge3678c6"
    "sec:orge22a7b9"
    "sec:org08d0129"
    "sec:org7cf7379"
    "sec:orgf4f3729"
    "sec:org38ffc30"
    "cpp_functions"
    "sec:org720babf"
    "sec:org3647866"
    "sec:orgec818d3"
    "sec:org4e7dcd0"
    "sec:org26a6ced"
    "sec:org4beb940"
    "sec:org67534d8"
    "sec:orgbd5b029"
    "sec:org01bcd22"
    "sec:org0ba38ad"
    "sec:org0e55fea"
    "sec:orgddcebd1"
    "cpp_struct"
    "sec:orgf69c929"))
 :latex)

